Source/Web/SaveTheSnails.Web/Areas/Coordinators/Controllers/MissionsController.cs
namespace SaveTheSnails.Web.Areas.Coordinators.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using SaveTheSnails.Data;
    using SaveTheSnails.Web.Controllers;
    using SaveTheSnails.Web.Areas.Coordinators.ViewModels;

    using Kendo.Mvc.UI;
    using Kendo.Mvc.Extensions;
    using SaveTheSnails.Data.Models;
    using SaveTheSnails.Web.Services;
    using SaveTheSnails.Common;


    public class MissionsController : BaseController
    {
        private SchedulerMissionService missionService;

        public MissionsController(IAppData data)
            : base(data)
        {
            this.missionService = new SchedulerMissionService(this.Data, this.CurrentUser);
        }

        public ActionResult Schedule()
        {
            return View();
        }

        public JsonResult Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(missionService.GetAll().ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Create([DataSourceRequest] DataSourceRequest request, MissionViewModel mission)
        {
            if (ModelState.IsValid)
            {
                mission.CoordinatorID = this.Data.Coordinators.All()
                                        .FirstOrDefault(c => c.User.UserName == this.CurrentUser.UserName).Id;
                this.missionService.Insert(mission, ModelState);
            }

            return Json(new[] { mission }.ToDataSourceResult(request, ModelState));
        }

        public virtual ActionResult Update([DataSourceRequest] DataSourceRequest request, MissionViewModel meeting)
        {

            if (true)
            {
                Success("Test", true);

                 ModelState.AddModelError("update-error", "Нямате право");
                 ModelState.AddModelError("update-error2", "Нямате желание");
            }
            else 
            {

                if (ModelState.IsValid)
                {
                    missionService.Update(meeting, ModelState);
                }
            }
            
            

            return Json(new[] { meeting }.ToDataSourceResult(request, ModelState));
        }

        public virtual JsonResult Destroy([DataSourceRequest] DataSourceRequest request, MissionViewModel meeting)
        {
            if (ModelState.IsValid)
            {
                missionService.Delete(meeting, ModelState);
            }

            return Json(new[] { meeting }.ToDataSourceResult(request, ModelState));
        }

        //TODO : add in Where clause if region of problem is the same with region of current user
        public ActionResult GetProblemsList()
        {
            if (User.IsInRole(GlobalConstants.AdminRole))
            {
                
            }


            var coordinatorRegion = this.Data.Coordinators.All()
                                                    .FirstOrDefault(c => c.User.UserName == this.CurrentUser.UserName).RegionID;

            var problems = this.Data.Problems.All()
                                        .Where(p => p.MissionID == null || p.Location.RegionID == coordinatorRegion)
                                        .Project().To<ProblemViewModel>();

            return Json(problems, JsonRequestBehavior.AllowGet);
        }

    }
}

Source/Web/SaveTheSnails.Web/Areas/Users/Controllers/ProblemController.cs
namespace SaveTheSnails.Web.Areas.Users.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using System.Web;
    using System.Web.Mvc;

    using Microsoft.AspNet.Identity;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using SaveTheSnails.Data;
    using SaveTheSnails.Data.Models;
    using SaveTheSnails.Web.Areas.Users.ViewModels;
    using SaveTheSnails.Web.Controllers;
    using SaveTheSnails.Web.Infrastructure.Populators;
    using Kendo.Mvc.UI;
    using Kendo.Mvc.Extensions;
    using SaveTheSnails.Common;
    using System.Net;

    [Authorize]
    public class ProblemController : BaseController
    {
        private IDropDownListPopulator populator;

        public ProblemController(IAppData data, IDropDownListPopulator populator)
            : base(data)
        {
            this.populator = populator;
        }

        // GET: Users/Problem
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult All(FilterProblemsViewModel filter)
        {
            return View(filter);
        }


        [HttpPost]
        public ActionResult ReadProblems([DataSourceRequest]DataSourceRequest request, int? category, int? region)
        {
            var problemsQuery = this.Data.Problems.All();

            if (category != null)
            {
                problemsQuery = problemsQuery.Where(t => t.CategoryID == category);
            }

            if (region != null)
            {
                problemsQuery = problemsQuery.Where(t => t.Location.RegionID == region);
            }

            var problems = problemsQuery
                            .Project()
                            .To<AllProblemsListViewModel>();

            return Json(problems.ToDataSourceResult(request));
        }

        [HttpGet]
        public ActionResult Register()
        {
            var registerProblemViewModel = new RegisterProblemViewModel
            {
                Categories = this.populator.GetCategories()
            };

            return View(registerProblemViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterProblemViewModel model)
        {

            if (model != null && ModelState.IsValid)
            {
                var dbProblem = Mapper.Map<Problem>(model);
                dbProblem.Reporter = this.CurrentUser;

                var dbPictures = this.MapPictures(model.UploadedPictures);
                dbProblem.Pictures.AddRange(dbPictures);

                this.Data.Problems.Add(dbProblem);
                this.Data.SaveChanges();

                Success(string.Format(GlobalConstants.SuccsessAddedProblem), true);
                return this.RedirectToAction("Register");
            }

            return this.View(model);
        }

        public ActionResult Details(int id)
        {
            var problem = this.Data
                .Problems
                .All()
                .Where(t => t.Id == id)
                .Project()
                .To<ProblemDetailsVewModel>()
                .FirstOrDefault();

            if (problem == null)
            {
                throw new HttpException(404, "Problem not found");
            }

            return View(problem);
        }

        [HttpPost]
        public ActionResult JoinToMission(int missionID)
        {
            var mission = this.Data.Missions.GetById(missionID);
            mission.JoinedUsers.Add(this.CurrentUser);
            this.Data.SaveChanges();

            var filter = new FilterProblemsViewModel();

            Success(string.Format(GlobalConstants.SuccsessJoinMission + " " + mission.Title), true);

            return View("All", filter);
        }

        [HttpPost]
        public ActionResult LeaveMission(int missionID)
        {
            var mission = this.Data.Missions.GetById(missionID);
            mission.JoinedUsers.Remove(this.CurrentUser);
            this.Data.SaveChanges();

            var filter = new FilterProblemsViewModel();

            Success(string.Format(GlobalConstants.SuccsessLeaveMission+ " " + mission.Title), true);

            return View("All", filter);
        }

        public ActionResult JoinedUsersToMission(int id)
        {
            if (!Request.IsAjaxRequest())
            {
                Response.StatusCode = (int)HttpStatusCode.Forbidden;
                return this.Content("This action can be invoke only by AJAX call");
            }

            var joinedUsers = this.Data.Missions
                                        .GetById(id)
                                        .JoinedUsers.Select(u=>u.UserName);

            return this.Content(String.Join(",", joinedUsers));
        }

        public ActionResult GetCategories()
        {
            return Json(this.populator.GetCategories(), JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetRegions()
        {
            return Json(this.populator.GetRegions(), JsonRequestBehavior.AllowGet);
        }

        public FileContentResult GetPicture(int id)
        {
            var picture = this.Data.Pictures.GetById(id);
            return picture.File != null ? new FileContentResult(picture.File, picture.ContentType) : null;
        }

        private ICollection<Picture> MapPictures(ICollection<HttpPostedFileBase> uploadedPictures)
        {
            ICollection<Picture> dbPictures = new List<Picture>(); ;

            foreach (var picture in uploadedPictures)
            {
                if (picture != null)
                {
                    using (var memory = new MemoryStream())
                    {
                        picture.InputStream.CopyTo(memory);

                        var dbPicture = new Picture
                        {
                            File = memory.GetBuffer(),
                            FileName = picture.FileName,
                            ContentType = picture.ContentType
                        };

                        dbPictures.Add(dbPicture);
                    }
                }
            }

            return dbPictures;
        }
    }
}

Source/Web/SaveTheSnails.Web/Views/Shared/_Alerts.cshtml
@using SaveTheSnails.Web.Infrastructure.Helpers
@{
    var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

    if (alerts.Any())
    {
        <hr />
    }

    foreach (var alert in alerts)
    {
        var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;
        <div class="alert alert-@alert.AlertStyle @dismissableClass">
            @if (alert.Dismissable)
            {
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            }
            @Html.Raw(alert.Message)
        </div>
    }
}

Source/Web/SaveTheSnails.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Save The Snails</title>
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
    @Styles.Render("~/Content/custom")
    @*@Styles.Render("~/Content/googlemaps")*@
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDsv_ABTjEUdDpbfsptt7rGhRGO-QtLQkE&v=3.exp&libraries=places">
    </script>
   
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Save The Snails_test2", "Index", "Home", new { area = string.Empty }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home", new { area = string.Empty }, null)</li>*@
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Problems<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Register", "Register", "Problem", new { area = "Users" }, null)</li>
                            <li>@Html.ActionLink("View All", "All", "Problem", new { area = "Users" }, null)</li>
                        </ul>
                    </li>
                        if (User.IsInRole(GlobalConstants.CoordinatorRole) || User.IsInRole(GlobalConstants.AdminRole))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Coordinators<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Schedule", "Schedule", "Missions", new { area = "Coordinators" }, null)</li>
                                </ul>
                            </li>
                        }

                        if (User.IsInRole(GlobalConstants.AdminRole))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Users", "Index", "Users", new { area = "Administration" }, null)</li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @{ Html.RenderPartial("_Alerts"); }
        @RenderBody()
        <hr />
        <footer class="well">
            <div class="row">
                <div class="col-md-offset-3">
                    <img src="~/img/snail3.gif" />
                </div>
            </div>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Source/Web/SaveTheSnails.Web/Views/Shared/_Map.cshtml
<input id="pac-input" class="controls" type="text" placeholder="Search Box">
<div id="map-canvas"></div>